Fixed a regression with xonfig styles
The "xonfig styles" command was reporting
AttributeError: module 'pygments' has no attribute 'styles'

Now we import the styles packages explicitly