Hide the full traceback by default in the shell.
The functionality can be controlled with the environment variable $XONSH_SHOW_TRACEBACK

If the that variable is not set, the default is to hide the traceback but with a extra notice:
mel@home ~ $x = {foo:1, bar}
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK=True
ValueError: Dict doesn't have the same number of keys as values
mel@home ~ $