fix(cwd): Fix exception in case of running command being in removed directory on macOS (#6570)
### Before

macOS:
```xsh
cd /tmp
mkdir dir
cd dir
touch file
# Remove or move /tmp/dir to trash
ls
```
Result:
```xsh
Traceback (most recent call last):                                      
  File                                                                  
"/Users/pc/.local/xonsh-env/lib/python3.14/site-packages/xonsh/main.py",
line 1267, in main                                                      
    sys.exit(main_xonsh(args))                                          
             ~~~~~~~~~~^^^^^^                                           
  File                                                                  
"/Users/pc/.local/xonsh-env/lib/python3.14/site-packages/xonsh/main.py",
line 1314, in main_xonsh                                                
    shell.shell.cmdloop()                                               
    ~~~~~~~~~~~~~~~~~~~^^                                               
  File "/Users/pc/.local/xonsh-env/lib/python3.14/site-packages/xonsh/sh
ells/ptk_shell/__init__.py", line 561, in cmdloop                       
    line = self.precmd(line)                                            
  File "/Users/pc/.local/xonsh-env/lib/python3.14/site-packages/xonsh/sh
ells/base_shell.py", line 375, in precmd                                
    self.precwd = os.getcwd()                                           
                  ~~~~~~~~~^^                                           
PermissionError: [Errno 1] Operation not permitted                      
Xonsh encountered an issue during launch.                               
Please report to https://github.com/xonsh/xonsh/issues                  
Failback to /bin/zsh                           
```

### After

```xsh
ls
# ls: .: Operation not permitted
# xonsh: working directory does not exist: /private/tmp/dir
cd ..
```

## For community
⬇️ **Please click the 👍 reaction instead of leaving a `+1` or 👍
comment**

Co-authored-by: Andy Kipp <123@321.123>