allow test_raise_subproc_error_with_show_traceback to be run locally
previously, this succeeded in CI, but always failed locally with the following error:
```
_____________________________________________________________________ test_raise_subproc_error_with_show_traceback[True] _____________________________________________________________________

monkeypatch = <_pytest.monkeypatch.MonkeyPatch object at 0x76f6ba8882e0>, interactive = True

    @skip_if_on_windows
    @pytest.mark.parametrize("interactive", [True, False])
    def test_raise_subproc_error_with_show_traceback(monkeypatch, interactive):
        out, err, ret = run_xonsh(
            "$COLOR_RESULTS=False\n$RAISE_SUBPROC_ERROR=False\n$XONSH_SHOW_TRACEBACK=False\nls nofile",
            interactive=interactive,
            single_command=True,
        )
        assert ret != 0
>       assert re.match("ls.*No such file or directory\n", out)
E       assert None
E        +  where None = <function match at 0x76f6bcd0cd30>('ls.*No such file or directory\n', "\x1b]0;ls | jyn@pop-os: ~/src/xonsh | xonsh\x07ls: cannot access 'nofile': No such file or directory\n")
E        +    where <function match at 0x76f6bcd0cd30> = re.match

tests/test_integrations.py:1190: AssertionError
```

the problem was that the following string was prepended before the error message:
```
\x1b]0;ls | jyn@pop-os: ~/src/xonsh | xonsh\x07l
```

that in turn came from [`BaseShell.settitle`](https://github.com/xonsh/xonsh/blob/66c0490d37581021e0cb4397d7bf0f4c110e0fa6/xonsh/base_shell.py#L570),
which always prepends at least the escape codes even when TITLE is set to an empty string.

avoid this issue by mimicking a dumb terminal in tests, in which case `settitle` doesn't add any title at all.

note that this originally used TERM=dumb; but that hung due to https://github.com/xonsh/xonsh/issues/5462. use TERM=linux instead to work around the issue.