fix(Windows): Fixed CDLL exception in MSYS2 when running xonsh (#6176)
Fixed exception in https://www.msys2.org/

```xsh
Traceback (most recent call last):
  File "/usr/bin/xonsh", line 3, in <module>
    from xonsh.main import main
  File "/usr/lib/python3.12/site-packages/xonsh/main.py", line 12, in <module>
    import xonsh.procs.pipelines as xpp
  File "/usr/lib/python3.12/site-packages/xonsh/procs/pipelines.py", line 14, in <module>
    import xonsh.procs.jobs as xj
  File "/usr/lib/python3.12/site-packages/xonsh/procs/jobs.py", line 273, in <module>
    LIBC.pthread_sigmask.restype = ctypes.c_int
    ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/xonsh/lib/lazyasd.py", line 56, in __getattribute__
    obj = self._lazy_obj()
          ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/xonsh/lib/lazyasd.py", line 48, in _lazy_obj
    obj = d["load"]()
          ^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/xonsh/platform.py", line 581, in LIBC
    libc = ctypes.CDLL("cygwin1.dll")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ctypes/__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: No such file or directory

```

## For community
⬇️ **Please click the 👍 reaction instead of leaving a `+1` or 👍
comment**

---------

Co-authored-by: Shevtsоvа Liliiа <shevtsova.liliya@gmail.com>
Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>
Co-authored-by: Gil Forsyth <gforsyth@users.noreply.github.com>
Co-authored-by: 1 <1@1.1>