fix: Fix tests that fail on NixOS (#6132)
Closes #5569
cc https://github.com/NixOS/nixpkgs/pull/497851

I'm going to fix errors that I see here:

```xsh
docker run --rm -it nixos/nix bash
nix-shell -p python3
python3 -m venv venv
source venv/bin/activate
git clone https://github.com/xonsh/xonsh
cd xonsh
pip install '.[test]'

# to fix tests/test_man.py::test_man_completion[man-exp1] - FileNotFoundError: [Errno 2] No such file or directory: 'col'
nix profile add --extra-experimental-features nix-command --extra-experimental-features flakes 'nixpkgs#util-linux'

python -m pytest
```
Fixed:
```xsh
++ FAILED tests/built_ins/test_tracer.py::test_trace_in_script - assert 1 == 0
++ FAILED tests/platform/test_platform.py::test_githash_value_error - AssertionError: assert 'Mar 10 14:15:14 2026' is None
++ FAILED tests/shell/test_ptk_highlight.py::test_xonsh_lexer_no_win[ls-bin-0] - Failed: Token (Token.Name.Builtin, '/bin/ls') missing: [(Token.Text.Whitespace, ''), (Token.Operator, '/'), (Token.Name.Builtin, 'bin'), (Token.Operator, '/'), (Token.Name, 'ls'), (Token.Text, ' '), (Token.Op...
++ FAILED tests/test_builtins.py::test_repath_backslash - AssertionError: assert set() == {'~/\\w\\w.*'}
++ FAILED tests/test_integrations.py::test_loading_correctly[True] - AssertionError: assert 'AAA /xonsh-dev/xonsh/__init__.py BBB' in 'AAA /xonsh-dev/venv/lib/python3.12/site-packages/xonsh/__init__.py BBB'
++ FAILED tests/test_integrations.py::test_loading_correctly[False] - AssertionError: assert 'AAA /xonsh-dev/xonsh/__init__.py BBB' in 'AAA /xonsh-dev/venv/lib/python3.12/site-packages/xonsh/__init__.py BBB'
++ FAILED tests/test_man.py::test_man_completion[yes-exp0] - FileNotFoundError: [Errno 2] No such file or directory: 'col'
++ FAILED tests/test_man.py::test_man_completion[man-exp1] - FileNotFoundError: [Errno 2] No such file or directory: 'col'
```
Ignored (future PR with fix is welcome! I think it's related to bash
completer installation on Nix):
```xsh
FAILED tests/completers/test_bash_completer.py::test_bash_completer[command_context0-completions0-5] - AssertionError: assert (set() == {'--debug', '--debugger'}
FAILED tests/completers/test_bash_completer.py::test_bash_completer[command_context1-completions1-0] - assert (set() == {"'spaced dir... "'testdir/'"}
FAILED tests/completers/test_bash_completer.py::test_bash_completer[command_context2-completions2-2] - AssertionError: assert (set() == {'~/A', '~/c'...', '~/u', ...}
FAILED tests/completers/test_bash_completer.py::test_bash_completer[command_context3-completions3-1] - assert (set() == {"'spaced dir... "'testdir/'"}
FAILED tests/completers/test_bash_completer.py::test_quote_handling[command_context0-completions0-4] - AssertionError: assert (set() == {'/proc/'}
FAILED tests/completers/test_bash_completer.py::test_quote_handling[command_context1-completions1-5] - assert (set() == {"'/proc/'"}
FAILED tests/completers/test_bash_completer.py::test_quote_handling[command_context2-completions2-5] - assert (set() == {"'/proc/"}
FAILED tests/completers/test_bash_completer.py::test_quote_handling[command_context3-completions3-6] - assert (set() == {"'/proc/'"}
FAILED tests/completers/test_bash_completer.py::test_quote_handling[command_context4-completions4-10] - assert (set() == {'"""/proc/"""'}
FAILED tests/completers/test_bash_completer.py::test_quote_handling[command_context5-completions5-4] - assert (set() == {"'./spaced dir/'"}
FAILED tests/completers/test_bash_completer.py::test_quote_handling[command_context6-completions6-5] - assert (set() == {"'./spaced dir/'"}
FAILED tests/completers/test_bash_completer.py::test_quote_handling[command_context7-completions7-5] - assert (set() == {"'./spaced dir/"}
FAILED tests/completers/test_bash_completer.py::test_quote_handling[command_context8-completions8-6] - assert (set() == {"'./spaced dir/'"}
FAILED tests/completers/test_bash_completer.py::test_bash_completer_empty_prefix - AssertionError: assert False
FAILED tests/completers/test_bash_completer.py::test_equal_sign_arg[command_context0-completions0-3-False] - AssertionError: assert (set() == {'status='}
FAILED tests/completers/test_bash_completer.py::test_equal_sign_arg[command_context1-completions1-3-True] - AssertionError: assert (set() == {'--utc'}
FAILED tests/completers/test_bash_completer.py::test_equal_sign_arg[command_context2-completions2-2-True] - AssertionError: assert (set() == {'progress'}
FAILED tests/completers/test_bash_completer.py::test_equal_sign_arg[command_context3-completions3-3-False] - AssertionError: assert (set() == {'/etc/'}
FAILED tests/completers/test_bash_completer.py::test_equal_sign_arg[command_context4-completions4-8-True] - AssertionError: assert (set() == {'/dev/null'}
```

## For community
⬇️ **Please click the 👍 reaction instead of leaving a `+1` or 👍
comment**

---------

Co-authored-by: Andy Kipp <123@321.123>
Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>